"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
type Booking = Record<string, unknown> & { id: string; first_name: string; last_name: string; event_type: string; pickup_date: string; status: string; internal_notes?: string; photo_id_paths?: string[] };
export function AdminConsole() {
  const [bookings, setBookings] = useState<Booking[]>([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [range, setRange] = useState({ from: "", to: "" }); const [message, setMessage] = useState("");
  useEffect(() => { void (async () => { const query = new URLSearchParams({ ...(search ? { search } : {}), ...(status ? { status } : {}) }); const response = await fetch(`/api/admin/bookings?${query}`); if (response.status === 401) window.location.href = "/admin/login"; else setBookings((await response.json()).bookings ?? []); })(); }, [search, status]);
  async function update(id: string, values: { status?: string; internal_notes?: string }) { await fetch("/api/admin/bookings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, ...values }) }); setBookings((current) => current.map((booking) => booking.id === id ? { ...booking, ...values } : booking)); }
  async function exportArchive() { if (!range.from || !range.to || !window.confirm("Export bookings and private attachments for this date range?")) return; const response = await fetch("/api/admin/export", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...range, confirm: true }) }); if (!response.ok) { setMessage((await response.json()).error); return; } const blob = await response.blob(); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `booking-archive-${range.from}-to-${range.to}.zip`; link.click(); URL.revokeObjectURL(link.href); }
  async function signedLink(path: string) { const response = await fetch(`/api/admin/photo-link?path=${encodeURIComponent(path)}`); const { url, error } = await response.json(); if (url) window.open(url, "_blank", "noopener,noreferrer"); else setMessage(error); }
  async function deleteBooking(id: string) { if (!window.confirm("Permanently delete this booking and its private photo IDs?")) return; const response = await fetch("/api/admin/bookings", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, confirm: true }) }); if (!response.ok) { setMessage((await response.json()).error); return; } setBookings((current) => current.filter((booking) => booking.id !== id)); }
  return <main className="mx-auto max-w-6xl space-y-6 px-6 py-10"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-muted-foreground">Peppermint Audio</p><h1 className="text-3xl font-semibold">Booking management</h1></div><Button variant="outline" onClick={async () => { await fetch("/api/admin/logout", { method: "POST" }); window.location.href = "/admin/login"; }}>Sign out</Button></div><section className="flex flex-wrap gap-2"><input placeholder="Search name, email or event" value={search} onChange={(e) => setSearch(e.target.value)} className="rounded border bg-background p-2" /><select value={status} onChange={(e) => setStatus(e.target.value)} className="rounded border bg-background p-2"><option value="">All statuses</option>{["submitted", "confirmed", "completed", "cancelled"].map((value) => <option key={value}>{value}</option>)}</select><Button onClick={() => setSearch(search)}>Search</Button></section><section className="rounded border p-4"><h2 className="mb-3 font-semibold">Date-range archive export</h2><div className="flex flex-wrap gap-2"><input type="date" value={range.from} onChange={(e) => setRange({ ...range, from: e.target.value })} className="rounded border bg-background p-2" /><input type="date" value={range.to} onChange={(e) => setRange({ ...range, to: e.target.value })} className="rounded border bg-background p-2" /><Button onClick={() => void exportArchive()}>Export ZIP</Button></div></section>{message && <p className="text-sm text-destructive">{message}</p>}<div className="space-y-4">{bookings.map((booking) => <article key={booking.id} className="rounded border p-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold">{booking.first_name} {booking.last_name} — {booking.event_type}</h2><p className="text-sm text-muted-foreground">{String(booking.email)} · {booking.pickup_date} to {String(booking.dropoff_date)}</p><p className="text-sm">{String(booking.event_address)}</p></div><select value={booking.status} onChange={(e) => void update(booking.id, { status: e.target.value })} className="h-9 rounded border bg-background px-2">{["submitted", "confirmed", "completed", "cancelled"].map((value) => <option key={value}>{value}</option>)}</select></div><textarea defaultValue={booking.internal_notes ?? ""} onBlur={(e) => void update(booking.id, { internal_notes: e.target.value })} placeholder="Internal notes" className="mt-3 min-h-20 w-full rounded border bg-background p-2 text-sm" />{booking.photo_id_paths?.length ? <div className="mt-2 flex gap-2">{booking.photo_id_paths.map((path) =>   <Button key={path} variant="outline" size="sm" onClick={() => void signedLink(path)}>View photo ID</Button>)}</div> : null}<Button variant="destructive" size="sm" className="mt-3" onClick={() => void deleteBooking(booking.id)}>Delete booking</Button></article>)}</div></main>;
}
